# Generated by Django 4.0 on 2023-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(auto_now_add=True)),
                ('orden', models.IntegerField()),
                ('imagen', models.CharField(max_length=500)),
                ('pagina_detalles', models.CharField(max_length=500)),
                ('tipoEvento', models.CharField(choices=[('N', 'Noticia'), ('E', 'Evento')], default='N', max_length=1)),
            ],
            options={
                'ordering': ['orden'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
