version: "3"

services:
  db-gia:
    image: postgres:12.14   
    env_file: .env_prod    
    volumes:
      - db_gia_prod:/var/lib/postgresql/data/pgdata

  web-gia:
    container_name: web-gia
    build:
      context: ./code/giaapp
      dockerfile: Dockerfile
      args:
        - DJANGO_ENV=production 
    env_file: .env_prod           
    command: giaapp/manage.py collectstatic --no-input
    command: python giaapp/manage.py runserver 0.0.0.0:8000
    ports:
      - '9002:8000'
    volumes: 
      - ./code:/giaapp
    depends_on:
      - db-gia
  
volumes:
  db_gia_prod:
    external: true